Tetris/config/routes.rb
Rails.application.routes.draw do
  resources :highscores, only: [:index, :new, :create]

  root 'home#index'
  post 'create' => 'highscores#create'

end

Tetris/app/models/highscore.rb
class Highscore < ActiveRecord::Base
  def self.top(n)
    self.limit(n).order('score desc')
  end
end

Tetris/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Tetris/app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  before_action :set_highscore, only: [:show, :edit, :update, :destroy]

  # GET /highscores
  # GET /highscores.json
  def index
    @highscores = Highscore.top(10)
  end

  # GET /highscores/1
  # GET /highscores/1.json
  def show
  end

  # GET /highscores/new
  def new
    @highscore = Highscore.new
  end

  # GET /highscores/1/edit
  def edit
  end

  # POST /highscores
  # POST /highscores.json
  def create
    @highscore = Highscore.new(highscore_params)

    respond_to do |format|
      if @highscore.save
        format.json { render json: @highscore, status: :created}
      else
        format.html { render :new }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highscores/1
  # PATCH/PUT /highscores/1.json
  def update
    respond_to do |format|
      if @highscore.update(highscore_params)
        format.html { redirect_to @highscore, notice: 'Highscore was successfully updated.' }
        format.json { render :show, status: :ok, location: @highscore }
      else
        format.html { render :edit }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highscores/1
  # DELETE /highscores/1.json
  def destroy
    @highscore.destroy
    respond_to do |format|
      format.html { redirect_to highscores_url, notice: 'Highscore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highscore
      @highscore = Highscore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highscore_params
      params.require(:highscore).permit(:name, :score)
    end
end

Tetris/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Tetris/app/helpers/application_helper.rb
module ApplicationHelper
end

Tetris/app/helpers/highscores_helper.rb
module HighscoresHelper
end

Tetris/app/views/highscores/_form.html.erb
<%= form_for(@highscore) do |f| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>

      <ul>
      <% @highscore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Tetris/app/views/highscores/edit.html.erb
<h1>Editing Highscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @highscore %> |
<%= link_to 'Back', highscores_path %>

Tetris/app/views/highscores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Highscores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>
    <col width="130">
    <col width="130">
    <% @highscores.each do |highscore| %>
      <tr>
        <td><%= highscore.name %></td>
        <td><%= highscore.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Tetris/app/views/highscores/new.html.erb
<!-- <h1>New Highscore</h1>

<%= render 'form' %>

<%= link_to 'Back', highscores_path %>
 -->

Tetris/app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @highscore.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @highscore.score %>
</p>

<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

Tetris/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tetris</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>